import RequestHandler from "../request-handler";
import { ENDPOINT } from "../endpoint";

// API Instances
export const AuthRegisterApi     = new RequestHandler(ENDPOINT.AUTH_REGISTER);
export const AuthLoginApi        = new RequestHandler(ENDPOINT.AUTH_LOGIN);
export const AuthMeApi           = new RequestHandler(ENDPOINT.AUTH_ME);
export const AuthChangePwApi     = new RequestHandler(ENDPOINT.AUTH_CHANGE_PW);
export const AuthAdminResetPwApi = new RequestHandler(ENDPOINT.AUTH_ADMIN_RESET_PW);
export const HealthApi = new RequestHandler(ENDPOINT.HEALTH);
export const AvailableModelsApi = new RequestHandler(ENDPOINT.AVAILABLE_MODELS);
export const HybridQueryApi = new RequestHandler(ENDPOINT.HYBRID_QUERY);
export const PdfUploadApi = new RequestHandler(ENDPOINT.PDF_UPLOAD);
export const PdfUploadFromUrlApi = new RequestHandler(ENDPOINT.PDF_UPLOAD_FROM_URL);
export const PdfUploadFromUrlsApi = new RequestHandler(ENDPOINT.PDF_UPLOAD_FROM_URLS);
export const DriveFolderItemsApi = new RequestHandler(ENDPOINT.DRIVE_FOLDER_ITEMS);
export const PdfCollectionsApi = new RequestHandler(ENDPOINT.PDF_COLLECTIONS);
export const PdfCollectionApi = new RequestHandler(ENDPOINT.PDF_COLLECTION);
export const PublicLinksApi = new RequestHandler(ENDPOINT.PUBLIC_LINKS);
export const PublicLinkApi = new RequestHandler(ENDPOINT.PUBLIC_LINK);
export const PublicLinkActivateApi = new RequestHandler(ENDPOINT.PUBLIC_LINK_ACTIVATE);
export const ChatUploadApi = new RequestHandler(ENDPOINT.CHAT_UPLOAD);
export const ChatCollectionsApi = new RequestHandler(ENDPOINT.CHAT_COLLECTIONS);
export const ChatCollectionApi = new RequestHandler(ENDPOINT.CHAT_COLLECTION);
export const ChatCollectionPreviewApi = new RequestHandler(ENDPOINT.CHAT_COLLECTION_PREVIEW);
export const SessionsApi = new RequestHandler(ENDPOINT.SESSIONS);
export const DbTablesApi = new RequestHandler(ENDPOINT.DB_TABLES);
export const DbTableApi = new RequestHandler(ENDPOINT.DB_TABLE);
export const DatabaseConnectionsApi = new RequestHandler(ENDPOINT.DATABASE_CONNECTIONS);
export const DatabaseConnectionApi = new RequestHandler(ENDPOINT.DATABASE_CONNECTION);
export const DatabaseConnectionActivateApi = new RequestHandler(ENDPOINT.DATABASE_CONNECTION_ACTIVATE);
